table Fact_Survey_Ratings
	lineageTag: 5b0894fc-9eb0-4e08-972b-29869e9d4206

	column Passenger_ID
		dataType: int64
		formatString: 0
		lineageTag: 2cde7e46-1146-4020-bd08-8af002f7e697
		summarizeBy: none
		sourceColumn: Passenger_ID

		annotation SummarizationSetBy = Automatic

	column Service_Name
		dataType: string
		lineageTag: 8bd19833-206e-4280-9d8d-ee8da0721dbf
		summarizeBy: none
		sourceColumn: Service_Name

		annotation SummarizationSetBy = Automatic

	column Rating
		dataType: int64
		formatString: 0
		lineageTag: 474406d6-cbdf-4151-921b-f177e42d772e
		summarizeBy: sum
		sourceColumn: Rating

		annotation SummarizationSetBy = Automatic

	column Service_Category
		dataType: string
		lineageTag: 4ac8e1f5-3cf0-426a-8fe4-33f86d784eb0
		summarizeBy: none
		sourceColumn: Service_Category

		annotation SummarizationSetBy = Automatic

	partition Fact_Survey_Ratings = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents("D:\Taarika\BA-BI-Documents (Taarika)\Projects - BI\Airlines Passenger Satisfaction Analysis\dataset\airline_passenger_satisfaction.csv"),[Delimiter=",", Columns=24, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"Gender", type text}, {"Age", Int64.Type}, {"Customer Type", type text}, {"Type of Travel", type text}, {"Class", type text}, {"Flight Distance", Int64.Type}, {"Departure Delay", Int64.Type}, {"Arrival Delay", Int64.Type}, {"Departure and Arrival Time Convenience", Int64.Type}, {"Ease of Online Booking", Int64.Type}, {"Check-in Service", Int64.Type}, {"Online Boarding", Int64.Type}, {"Gate Location", Int64.Type}, {"On-board Service", Int64.Type}, {"Seat Comfort", Int64.Type}, {"Leg Room Service", Int64.Type}, {"Cleanliness", Int64.Type}, {"Food and Drink", Int64.Type}, {"In-flight Service", Int64.Type}, {"In-flight Wifi Service", Int64.Type}, {"In-flight Entertainment", Int64.Type}, {"Baggage Handling", Int64.Type}, {"Satisfaction", type text}}),
				    #"Removed Blank Rows" = Table.SelectRows(#"Changed Type", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Blank Rows",{{"ID", "Passenger_ID"}, {"Customer Type", "Customer_Type"}, {"Type of Travel", "Type_of_Travel"}, {"Flight Distance", "Flight_Distance"}, {"Departure Delay", "Departure_Delay"}, {"Arrival Delay", "Arrival_Delay"}, {"Departure and Arrival Time Convenience", "Departure_Arrival_Convenience"}, {"Ease of Online Booking", "Ease_of_Online_Booking"}, {"Check-in Service", "Checkin_Service"}, {"Online Boarding", "Online_Boarding"}, {"Gate Location", "Gate_Location"}, {"On-board Service", "Onboard_Service"}, {"Seat Comfort", "Seat_Comfort"}, {"Leg Room Service", "Leg_Room_Service"}, {"Food and Drink", "Food_and_Drink"}, {"In-flight Service", "Inflight_Service"}, {"In-flight Wifi Service", "Inflight_Wifi"}, {"In-flight Entertainment", "Inflight_Entertainment"}, {"Baggage Handling", "Baggage_Handling"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Satisfaction_Binary", each if[Satisfaction] = "Satisfied" then 1 else 0),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Age_Group", each if [Age] < 18 then "Under 18"
				else if [Age] <= 25 then "18-25"
				else if [Age] <= 35 then "26-35"
				else if [Age] <= 45 then "36-45"
				else if [Age] <= 55 then "46-55"
				else if [Age] <= 65 then "56-65"
				else "65+"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom1",{{"Satisfaction_Binary", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type1", "Flight_Distance_Group", each if [Flight_Distance] <= 1000 then "Short Haul"
				else if [Flight_Distance] <= 2500 then "Medium Haul"
				else "Long Haul"),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Delay_Group", each if [Departure_Delay] = 0 then "No Delay"
				else if [Departure_Delay] <= 30 then "Minor Delay"
				else "Major Delay"),
				    #"Removed Other Columns" = Table.SelectColumns(#"Added Custom3",{"Passenger_ID", "Departure_Arrival_Convenience", "Ease_of_Online_Booking", "Checkin_Service", "Online_Boarding", "Gate_Location", "Onboard_Service", "Seat_Comfort", "Leg_Room_Service", "Cleanliness", "Food_and_Drink", "Inflight_Service", "Inflight_Wifi", "Inflight_Entertainment", "Baggage_Handling"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"Passenger_ID"}, "Attribute", "Value"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Service_Name"}, {"Value", "Rating"}}),
				    #"Added Custom4" = Table.AddColumn(#"Renamed Columns1", "Service_Category", each if [Service_Name] = "Ease_of_Online_Booking" 
				   or [Service_Name] = "Checkin_Service"
				   or [Service_Name] = "Online_Boarding"
				   or [Service_Name] = "Gate_Location"
				   or [Service_Name] = "Departure_Arrival_Convenience"
				then "Pre-Boarding"
				else if [Service_Name] = "Inflight_Wifi"
				   or [Service_Name] = "Inflight_Entertainment"
				   or [Service_Name] = "Inflight_Service"
				   or [Service_Name] = "Baggage_Handling"
				then "Essential Services"
				else "In-Flight Comfort"),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom4",{{"Service_Category", type text}}),
				    #"Removed Blank Rows1" = Table.SelectRows(#"Changed Type2", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Blank Rows1", each [Rating] > 0),
				    #"Filtered Rows1" = Table.SelectRows(#"Filtered Rows", each true)
				in
				    #"Filtered Rows1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

